# Generated by Django 5.1.7 on 2025-03-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_ingredients_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='vegetarian',
            field=models.BooleanField(default=True),
        ),
    ]
