# Generated by Django 5.1.7 on 2025-04-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_vegetarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='nutritional_info',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proteins',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sugar',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
    ]
